const { mapObjectKeysToValues } = require('./utils');

module.exports = {
	ActionTypes: {
		SOCKET_USER_CONNECTED: 1,
		SOCKET_USER_SAY: 2,
		SOCKET_USER_DISCONNECTED: 3,
		ROOM_INIT_WITH_ID: 4,
		USER_CONNECTED: 5,
		ROUND_START_REQUEST: 6,
		ROUND_START_SUCCESS: 7,
		ROUND_START_FAILED: 8,
		ROUND_END_REQUEST: 9,
		ROUND_END_SUCCESS: 10,
		ROUND_END_FAILED: 11,
		USER_DISCONNECTED: 12,
		HAVE_ENOUGH_PLAYERS: 13,
		ROUND_END_STATE_WAIT_COMPLETED: 14,
		RIGHT_ANSWER_FOUND: 15,
		WRONG_ANSWER_FOUND: 16,
		ADD_USER_LEADERBOARD_POINTS: 17,
		LEADERBOARD_UPDATE: 18,
		USER_HATCH_PERCENTAGE: 19,
		REFRESH_USERS_HATCH: 20,
		TELLER_PICK_ANSWER_SUCCESS: 28,
		TELLER_PICK_ANSWER_FAILED: 29,
		ROUND_IN_PROGRESS_REQUEST: 24,
		ROUND_IN_PROGRESS_SUCCESS: 25,
		ROUND_IN_PROGRESS_FAILED: 26,
		SOCKET_USER_PICK_ANSWER: 27,
		AUTOMATIC_TELLER_PICK_ANSWER_REQUEST: 28,
	},
	GameState: {
		IDLE: 0,
		ROUND_PICK_ANSWER: 1,
		ROUND_IN_PROGRESS: 2,
		ROUND_FINISHED: 3,
	},
	Symbols: {
		SYSTEM: Symbol('@@system'),
	}
};

module.exports.ActionTypes = mapObjectKeysToValues(module.exports.ActionTypes);
